# fly.toml app configuration file generated for b2b-template on 2024-11-20T00:25:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'b2b-template'
primary_region = 'cdg'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
